Repository swdotcom/swdc-vscode, pull requests merged in 2025-05, with the labels that each got.

#534 bump vscode engine version and dependencies
  package.json
  src/Util.ts
  src/command-helper.ts
  src/local/404.ts
  swdc-vscode-2.8.3.vsix
  swdc-vscode-2.8.4.vsix
  yarn.lock
Labels: dependencies

#538 prevent events when no jwt
  package.json
  src/Util.ts
  src/managers/TrackerManager.ts
  swdc-vscode-2.8.4.vsix
  swdc-vscode-2.8.5.vsix
  yarn.lock
Labels: bug

#547 Use swdc-tracker v1.6.0
  .vscode/launch.json
  package.json
  src/Constants.ts
  src/http/HttpClient.ts
  src/managers/ExtensionManager.ts
  src/managers/TrackerManager.ts
  src/websockets.ts
  yarn.lock
Labels: enhancement
